# Generated by Django 2.1.5 on 2019-04-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.CharField(default=100, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='shop/static/images/home/gallery2.jpg', upload_to='shop/static/images/home/'),
        ),
    ]
