# Generated by Django 2.2 on 2019-04-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190402_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='static/images/home/gallery2.jpg', upload_to='static/images/home/'),
        ),
    ]
