# Generated by Django 2.2 on 2019-04-26 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('hm_name', models.CharField(max_length=50)),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('mobile', models.CharField(max_length=10)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.register')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=10)),
                ('pay_method', models.CharField(max_length=50)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Address')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.products')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.register')),
            ],
        ),
    ]
