# Generated by Django 2.2 on 2019-04-27 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_order_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pay_method',
            new_name='payment_method',
        ),
    ]
