# Generated by Django 2.2 on 2019-05-15 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20190515_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.OrderStatus'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status_text',
            field=models.CharField(default='Order Placed', max_length=100),
        ),
    ]
